version: 2
updates:
  - package-ecosystem: docker
    directory: /images/base
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /images/dotnet8
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
