name: C++
on: [push, pull_request]
jobs:
  test:
    runs-on: cpp
    steps:
      - uses: actions/checkout@v4
      - run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - run: ctest --test-dir build --output-on-failure
